#!/bin/sh
# -------------------------------------------------------
# A shell script that use to run the Data handler server
# Written by     : Evarist Fangnikoue
# Email          : malevae@gmail.com
# Last updated on: 2018/20/08
# -------------------------------------------------------

EXIT_STATUS=0

#Checking the environment variable
global_script()
{
    ./global_script all
    EXIT_STATUS=$?
}


#run the emitter python file
run_script()
{

    if [ $EXIT_STATUS -eq 0 ]; then
    
        if [ -z $PYTHON ]; then
    
            exec "${HSBC_MINNING_HOME}/emitter/emitter.py" $@
        
        else
            $PYTHON "${HSBC_MINNING_HOME}/emitter/emitter.py" $@
        fi
        
   else
       exit
   fi
   
}

check_file()
{

    file_name="${HSBC_MINNING_HOME}/examples/data/account_holder.json"
    
    ./global_script check_file $file_name
    
    EXIT_STATUS=$?
    
    if [ $EXIT_STATUS -eq 1 ]; then
        ./global_script usage error no_file $file_name
        
    fi
    
}

#The startup script 
main()
{

    global_script
    
    check_file
    
    run_script
    
    exit 0
}

main